
name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.release.outputs.DOCKER }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 20.8.0

      - name: Install Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Login to GitHub
        run: |
          git config --global user.email "runner@users.noreply.github.com"
          git config --global user.name "runner"

      - name: Release
        id: release
        run: yarn release $GITHUB_REF_NAME

      - name: Building npm packages
        run: echo "building ${{ steps.release.outputs.NPM }}"

  docker:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: needs.build.outputs.docker != ''
    strategy:
      matrix:
        docker: ${{ fromJson(needs.build.outputs.docker) }}

    steps:
      - name: Building docker images
        run: echo "building ${{ matrix.docker }}"
