
name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 20.8.0

      - name: Install Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Release
        id: release
        run: yarn release $GITHUB_REF_NAME >> $GITHUB_OUTPUT

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - env:
          RELEASE: ${{ needs.build.outputs.release }}
        run: echo "$RELEASE"
